export default {
    INITIAL_LOAD: 'INITIAL_LOAD',
    INITIAL_LOAD_ERROR: 'INITIAL_LOAD_ERROR',
    INITIAL_LOAD_SUCCESS: 'INITIAL_LOAD_SUCCESS',
    UPDATE_CART: 'UPDATE_CART',
    RESET_CART: 'RESET_CART',
};
  